Env=Local
Browser=Chrome
ProjectName=UI Test Automation Framework
#Qa,Staging,Preprod
Environment=Qa
#Defect raising in jira
LogDefect=No
TestManagement=Jira
#Sending email or not
EmailSetUp=Yes
SenderEmail=testing27334@gmail.com
SenderPassword=bups bcek qhph nkds
recipientEmail=test456232312@gmail.com
#anildshiva@gmail.com
#shilparaddi100@gmail.com
#Jira Configuration
Base_Url=https://anildshiva.atlassian.net/
AuthKey=Basic YW5pbGRzaGl2YUBnbWFpbC5jb206QVRBVFQzeEZmR0YwZmZpZW54YWlLaWFDRnpfSGQ1OVhKLWNiV2VoUkQxNV9QN0tZblgwM1FJS2I0VHdXVFVaRzZsSV9GX05qNWVETE5BcmxfY05mMjVrNTVnV0s0WWJ3SERwM1VBQzA0bVowa1ZqTWFPMGZ3cWdDUktSeDBoVktULWdIYTJHdThRTTluV1JfSmRjQzdxWThrd1duVGlzbWhwSGdZdWlvalNGNXAyRmVfWXV1bHpRPUMwRTM4MjE0
ProjectKey=TA
#Db Configuration
HostName=127.0.0.1:3306
Database_UserName=root
Database_Password=root
#Change to Uat Prod or PreProd
DbEnv=Qa
DatabaseName=CovidData
Issue_Endpoint=rest/api/3/issue





