Env=Local
Browser=Chrome
ProjectName=UI Test Automation Framework
#Qa,Staging,Preprod
Environment=Qa
#Defect raising in jira
LogDefect=No
TestManagement=Jira
#Sending email or not
EmailSetUp=Yes
SenderEmail=testing27334@gmail.com
SenderPassword=bups bcek qhph nkds
recipientEmail=test456232312@gmail.com
#anildshiva@gmail.com
#shilparaddi100@gmail.com
#Jira Configuration
Base_Url=https://anildshiva-1739807022732.atlassian.net/
AuthKey=Basic YW5pbGRzaGl2YUBnbWFpbC5jb206QVRBVFQzeEZmR0YwcXBpUkZ1RU56OGJxeFhVbGFFUEZLajczRG5HSzE4bVNuc2ltM1FOVU5YOVk1NlhGaWRZdjVEdE1DY2dEYU1TUGlXUHpHSlJ2VUVaeEd5UnM3OVktc2tCeFM3OHFnUjRpSUppSElHSWZtWjhfTEhJTTk0VkFxeUszVDFYdV80MXptX1BRNncyYlJzNUJYU284WUpqVFl6SUxWWG1GNnRiWjBVNEFqbXdaQWxBPUIzQzY3OUUz
ProjectKey=SCRUM

#Db Configuration
HostName=127.0.0.1:3306
Database_UserName=root
Database_Password=root
#Change to Uat Prod or PreProd
DbEnv=Qa
DatabaseName=CovidData





