name: Run Tests & Send HTML Summary

on:
  push:
    branches: [ testing_github_action ]
  workflow_dispatch:

jobs:
  test_and_mail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven Tests
        run: mvn clean test

      - name: Zip HTML Report Folder
        run: |
          cd HtmlReports/ZipReport
          zip -r TestReport.zip TestReport
          echo "Zipped report created at HtmlReports/ZipReport/TestReport.zip"

      - name: Read test-summary.html
        id: summary
        shell: bash
        run: |
          echo "html_summary<<EOF" >> $GITHUB_OUTPUT
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_OUTPUT
          done < test-summary.html
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Use summary
        run: echo "${{ steps.summary.outputs.html_summary }}"